[package]
name = "backup"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "1.3", features = ["json"] }
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
smol_str = { version = "0.1", features = ["serde"] }
md5 = "0.7"
hex = "0.4"
dotenv = "0.15"
main_error = "0.1"